package generator

const alloyDiscoveryTemplate = `// ----------------------------------------------------------------------------
// Grafana Alloy starter configuration generated by ptdgen
// ----------------------------------------------------------------------------
// PLACEHOLDER: Update remote_write url to point to your Prometheus / Mimir.
// PLACEHOLDER: Update the files path to where you mount prometheus-file-sd.json.
// ----------------------------------------------------------------------------

discovery.file "generated_targets" {
  // Path to the file_sd JSON produced by ptdgen generate.
  files = ["/etc/alloy/file_sd/prometheus-file-sd.json"]
  refresh_interval = "30s"
}

prometheus.scrape "generated_targets" {
  targets    = discovery.file.generated_targets.targets
  forward_to = [prometheus.remote_write.default.receiver]
}

prometheus.remote_write "default" {
  endpoint {
    // PLACEHOLDER: replace with your Prometheus / Mimir remote_write URL.
    url = "http://mimir-nginx.monitoring.svc:80/api/v1/push"
  }
}
`

func buildAlloyDiscovery() []byte {
	return []byte(alloyDiscoveryTemplate)
}
